/**
 * generated by Scrooge 3.0.3
 */
package com.ahmedsoliman.rpc

import com.twitter.scrooge.{ThriftStruct, ThriftStructCodec}
import java.net.InetSocketAddress
import java.nio.ByteBuffer
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import scala.collection.mutable
import scala.collection.{Map, Set}
import com.twitter.util.Future
import com.twitter.conversions.time._
import com.twitter.finagle.{Service => FinagleService}
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.finagle.thrift.ThriftClientRequest
import com.twitter.finagle.SourcedException
import com.twitter.finagle.{Service => FinagleService}
import java.util.Arrays
import org.apache.thrift.transport.{TMemoryBuffer, TMemoryInputTransport, TTransport}


object HelloWorld {
  trait Iface {
    
    def getHelloWorld(): String
  }

  trait FutureIface {
    
    def getHelloWorld(): Future[String]
  }

  
  object GetHelloWorldArgs extends ThriftStructCodec[GetHelloWorldArgs] {
    val Struct = new TStruct("GetHelloWorldArgs")
  
    /**
     * Checks that all required fields are non-null.
     */
    def validate(_item: GetHelloWorldArgs) {
    }
  
    def encode(_item: GetHelloWorldArgs, _oproto: TProtocol) { _item.write(_oproto) }
    def decode(_iprot: TProtocol) = Immutable.decode(_iprot)
  
    def apply(_iprot: TProtocol): GetHelloWorldArgs = decode(_iprot)
  
    def apply(
    ): GetHelloWorldArgs = new Immutable(
    )
  
    def unapply(_item: GetHelloWorldArgs): Boolean = true
  
    object Immutable extends ThriftStructCodec[GetHelloWorldArgs] {
      def encode(_item: GetHelloWorldArgs, _oproto: TProtocol) { _item.write(_oproto) }
      def decode(_iprot: TProtocol) = {
        var _done = false
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case _ => TProtocolUtil.skip(_iprot, _field.`type`)
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
        new Immutable(
        )
      }
    }
  
    /**
     * The default read-only implementation of GetHelloWorldArgs.  You typically should not need to
     * directly reference this class; instead, use the GetHelloWorldArgs.apply method to construct
     * new instances.
     */
    class Immutable(
    ) extends GetHelloWorldArgs
  
  }
  
  trait GetHelloWorldArgs extends ThriftStruct
    with Product
    with java.io.Serializable
  {
    import GetHelloWorldArgs._
  
  
  
    override def write(_oprot: TProtocol) {
      GetHelloWorldArgs.validate(this)
      _oprot.writeStructBegin(Struct)
      _oprot.writeFieldStop()
      _oprot.writeStructEnd()
    }
  
    def copy(
    ): GetHelloWorldArgs = new Immutable(
    )
  
    override def canEqual(other: Any): Boolean = other.isInstanceOf[GetHelloWorldArgs]
  
    override def equals(other: Any): Boolean = runtime.ScalaRunTime._equals(this, other)
  
    override def hashCode: Int = runtime.ScalaRunTime._hashCode(this)
  
    override def toString: String = runtime.ScalaRunTime._toString(this)
  
  
    override def productArity: Int = 0
  
    override def productElement(n: Int): Any = n match {
      case _ => throw new IndexOutOfBoundsException(n.toString)
    }
  
    override def productPrefix: String = "GetHelloWorldArgs"
  }
  
  object GetHelloWorldResult extends ThriftStructCodec[GetHelloWorldResult] {
    val Struct = new TStruct("GetHelloWorldResult")
    val SuccessField = new TField("success", TType.STRING, 0)
  
    /**
     * Checks that all required fields are non-null.
     */
    def validate(_item: GetHelloWorldResult) {
    }
  
    def encode(_item: GetHelloWorldResult, _oproto: TProtocol) { _item.write(_oproto) }
    def decode(_iprot: TProtocol) = Immutable.decode(_iprot)
  
    def apply(_iprot: TProtocol): GetHelloWorldResult = decode(_iprot)
  
    def apply(
      success: Option[String] = None
    ): GetHelloWorldResult = new Immutable(
      success
    )
  
    def unapply(_item: GetHelloWorldResult): Option[Option[String]] = Some(_item.success)
  
    object Immutable extends ThriftStructCodec[GetHelloWorldResult] {
      def encode(_item: GetHelloWorldResult, _oproto: TProtocol) { _item.write(_oproto) }
      def decode(_iprot: TProtocol) = {
        var success: String = null
        var _got_success = false
        var _done = false
        _iprot.readStructBegin()
        while (!_done) {
          val _field = _iprot.readFieldBegin()
          if (_field.`type` == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 0 => { /* success */
                _field.`type` match {
                  case TType.STRING => {
                    success = {
                      _iprot.readString()
                    }
                    _got_success = true
                  }
                  case _ => TProtocolUtil.skip(_iprot, _field.`type`)
                }
              }
              case _ => TProtocolUtil.skip(_iprot, _field.`type`)
            }
            _iprot.readFieldEnd()
          }
        }
        _iprot.readStructEnd()
        new Immutable(
          if (_got_success) Some(success) else None
        )
      }
    }
  
    /**
     * The default read-only implementation of GetHelloWorldResult.  You typically should not need to
     * directly reference this class; instead, use the GetHelloWorldResult.apply method to construct
     * new instances.
     */
    class Immutable(
      val success: Option[String] = None
    ) extends GetHelloWorldResult
  
  }
  
  trait GetHelloWorldResult extends ThriftStruct
    with Product1[Option[String]]
    with java.io.Serializable
  {
    import GetHelloWorldResult._
  
    def success: Option[String]
  
    def _1 = success
  
    override def write(_oprot: TProtocol) {
      GetHelloWorldResult.validate(this)
      _oprot.writeStructBegin(Struct)
      if (success.isDefined) {
        val success_item = success.get
        _oprot.writeFieldBegin(SuccessField)
        _oprot.writeString(success_item)
        _oprot.writeFieldEnd()
      }
      _oprot.writeFieldStop()
      _oprot.writeStructEnd()
    }
  
    def copy(
      success: Option[String] = this.success
    ): GetHelloWorldResult = new Immutable(
      success
    )
  
    override def canEqual(other: Any): Boolean = other.isInstanceOf[GetHelloWorldResult]
  
    override def equals(other: Any): Boolean = runtime.ScalaRunTime._equals(this, other)
  
    override def hashCode: Int = runtime.ScalaRunTime._hashCode(this)
  
    override def toString: String = runtime.ScalaRunTime._toString(this)
  
  
    override def productArity: Int = 1
  
    override def productElement(n: Int): Any = n match {
      case 0 => success
      case _ => throw new IndexOutOfBoundsException(n.toString)
    }
  
    override def productPrefix: String = "GetHelloWorldResult"
  }
  
  class FinagledClient(
    val service: FinagleService[ThriftClientRequest, Array[Byte]],
    val protocolFactory: TProtocolFactory = new TBinaryProtocol.Factory,
    val serviceName: String = "",
    stats: StatsReceiver = NullStatsReceiver
  ) extends FutureIface {
    // ----- boilerplate that should eventually be moved into finagle:
  
    protected def encodeRequest(name: String, args: ThriftStruct) = {
      val buf = new TMemoryBuffer(512)
      val oprot = protocolFactory.getProtocol(buf)
  
      oprot.writeMessageBegin(new TMessage(name, TMessageType.CALL, 0))
      args.write(oprot)
      oprot.writeMessageEnd()
  
      val bytes = Arrays.copyOfRange(buf.getArray, 0, buf.length)
      new ThriftClientRequest(bytes, false)
    }
  
    protected def decodeResponse[T <: ThriftStruct](resBytes: Array[Byte], codec: ThriftStructCodec[T]) = {
      val iprot = protocolFactory.getProtocol(new TMemoryInputTransport(resBytes))
      val msg = iprot.readMessageBegin()
      try {
        if (msg.`type` == TMessageType.EXCEPTION) {
          val exception = TApplicationException.read(iprot) match {
            case sourced: SourcedException =>
              if (serviceName != "") sourced.serviceName = serviceName
              sourced
            case e => e
          }
          throw exception
        } else {
          codec.decode(iprot)
        }
      } finally {
        iprot.readMessageEnd()
      }
    }
  
    protected def missingResult(name: String) = {
      new TApplicationException(
        TApplicationException.MISSING_RESULT,
        name + " failed: unknown result"
      )
    }
  
    // ----- end boilerplate.
  
    private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
    private[this] object __stats_getHelloWorld {
      val RequestsCounter = scopedStats.scope("getHelloWorld").counter("requests")
      val SuccessCounter = scopedStats.scope("getHelloWorld").counter("success")
      val FailuresCounter = scopedStats.scope("getHelloWorld").counter("failures")
      val FailuresScope = scopedStats.scope("getHelloWorld").scope("failures")
    }
  
  
    def getHelloWorld(): Future[String] = {
      __stats_getHelloWorld.RequestsCounter.incr()
      this.service(encodeRequest("getHelloWorld", GetHelloWorldArgs())) flatMap { response =>
        val result = decodeResponse(response, GetHelloWorldResult)
        val exception =
          None
        exception.orElse(result.success.map(Future.value)).getOrElse(Future.exception(missingResult("getHelloWorld")))
      } rescue {
        case ex: SourcedException => {
          if (this.serviceName != "") { ex.serviceName = this.serviceName }
          Future.exception(ex)
        }
      } onSuccess { _ =>
        __stats_getHelloWorld.SuccessCounter.incr()
      } onFailure { ex =>
        __stats_getHelloWorld.FailuresCounter.incr()
        __stats_getHelloWorld.FailuresScope.counter(ex.getClass.getName).incr()
      }
    }
  }
  
  class FinagledService(
    iface: FutureIface,
    protocolFactory: TProtocolFactory
  ) extends FinagleService[Array[Byte], Array[Byte]] {
    // ----- boilerplate that should eventually be moved into finagle:
  
    protected val functionMap = new mutable.HashMap[String, (TProtocol, Int) => Future[Array[Byte]]]()
  
    protected def addFunction(name: String, f: (TProtocol, Int) => Future[Array[Byte]]) {
      functionMap(name) = f
    }
  
    protected def exception(name: String, seqid: Int, code: Int, message: String): Future[Array[Byte]] = {
      try {
        val x = new TApplicationException(code, message)
        val memoryBuffer = new TMemoryBuffer(512)
        val oprot = protocolFactory.getProtocol(memoryBuffer)
  
        oprot.writeMessageBegin(new TMessage(name, TMessageType.EXCEPTION, seqid))
        x.write(oprot)
        oprot.writeMessageEnd()
        oprot.getTransport().flush()
        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } catch {
        case e: Exception => Future.exception(e)
      }
    }
  
    protected def reply(name: String, seqid: Int, result: ThriftStruct): Future[Array[Byte]] = {
      try {
        val memoryBuffer = new TMemoryBuffer(512)
        val oprot = protocolFactory.getProtocol(memoryBuffer)
  
        oprot.writeMessageBegin(new TMessage(name, TMessageType.REPLY, seqid))
        result.write(oprot)
        oprot.writeMessageEnd()
  
        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } catch {
        case e: Exception => Future.exception(e)
      }
    }
  
    final def apply(request: Array[Byte]): Future[Array[Byte]] = {
      val inputTransport = new TMemoryInputTransport(request)
      val iprot = protocolFactory.getProtocol(inputTransport)
  
      try {
        val msg = iprot.readMessageBegin()
        functionMap.get(msg.name) map { _.apply(iprot, msg.seqid) } getOrElse {
          TProtocolUtil.skip(iprot, TType.STRUCT)
          exception(msg.name, msg.seqid, TApplicationException.UNKNOWN_METHOD,
            "Invalid method name: '" + msg.name + "'")
        }
      } catch {
        case e: Exception => Future.exception(e)
      }
    }
  
    // ---- end boilerplate.
  
    addFunction("getHelloWorld", { (iprot: TProtocol, seqid: Int) =>
      try {
        val args = GetHelloWorldArgs.decode(iprot)
        iprot.readMessageEnd()
        (try {
          iface.getHelloWorld()
        } catch {
          case e: Exception => Future.exception(e)
        }) flatMap { value: String =>
          reply("getHelloWorld", seqid, GetHelloWorldResult(success = Some(value)))
        } rescue {
          case e => Future.exception(e)
        }
      } catch {
        case e: TProtocolException => {
          iprot.readMessageEnd()
          exception("getHelloWorld", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
        }
        case e: Exception => Future.exception(e)
      }
    })
  }
}